### ISSUE TITLE
Minor hitch with default_mirror setting

### ISSUE THREAD

**Issue by kraken-jim** [NapoleonWils0n/davinci-resolve-freebsd-jail#1]
Hi!  Thank you very much for bringing your work to my attention.  I'm just beginning to explore it, but have one small patch to fix an error I encountered:
```
# debootstrap mantic /compat/ubuntu
I: Retrieving InRelease 
I: Retrieving Release 
E: Failed getting release file http://old-releases.ubuntu.com/ubuntu/dists/mantic/Release
```
I'll submit a PR shortly that fixed the problem for me.

Thanks again for sharing your work.

Jim

**Comment by NapoleonWils0n** [comment]
hi mate

i have installed Davinci Resolve 19.1 in a Rocky Linux jail

https://github.com/NapoleonWils0n/cerberus/blob/master/freebsd/rocky-linux-jail.org

but i havent got the audio working yet
because rocky linux uses pipewire and not pulseaudio

https://forums.FreeBSD.org/threads/rocky-linux-9-minimal-jail-working-need-to-figure-out-the-next-steps.94933/post-672793

**Comment by NapoleonWils0n** [comment]
hi mate

just got the audio working on rocky linux with pulseaudio
